import { facetValues, filterWithFacets } from "./search.mjs";
import { donationsGiftsBequestsDisplay, financialMetricDisplay, formatMoney, functionalAllocationDisplay, fundraisingAllocationOnly, sourceRecordLocator, taxonomyHeading, validActionUrl } from "./presentation.mjs";
import { correctionUrl } from "./corrections.mjs";

const state = { entities: [], similarities: [], filtered: [], selectedId: null, facets: {} };
const els = { search: document.querySelector("#search"), results: document.querySelector("#results"), count: document.querySelector("#result-count"), card: document.querySelector("#card"), feedback: document.querySelector("#feedback-link"), facets: document.querySelector("#facets") };
const esc = value => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const abn = entity => entity.external_identifiers?.find(item => item.scheme.toLowerCase() === "abn")?.value;
const httpUrl = value => /^https?:\/\//i.test(value ?? "") ? value : `https://${value}`;
const cardUrl = entity => entity.canonical_url ?? `${location.origin}${location.pathname}#${encodeURIComponent(entity.causebase_id)}`;
const label = value => value.split(":").at(-1).replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const list = (values, empty = "None recorded") => values?.length ? `<ul>${values.map(value => `<li>${esc(value)}</li>`).join("")}</ul>` : `<p>${empty}</p>`;

function citations(entity) { return new Map([...new Set([...(entity.summary_evidence_ids ?? []), ...(entity.evidence ?? []).map(item => item.evidence_id)])].map((id, index) => [id, index + 1])); }
function cite(ids, registry) { return (ids ?? []).filter(id => registry.has(id)).map(id => `<a class="citation" href="#reference-${registry.get(id)}" aria-label="Reference ${registry.get(id)}">[${registry.get(id)}]</a>`).join(" "); }
function syncUrl(push = false) { const params = new URLSearchParams(); if (els.search.value) params.set("q", els.search.value); for (const [group, values] of Object.entries(state.facets)) if (values.length) params.set(group, values.join(",")); window.history[push ? "pushState" : "replaceState"]({}, "", `${location.pathname}${params.size ? `?${params}` : ""}${state.selectedId ? `#${encodeURIComponent(state.selectedId)}` : ""}`); }
function readUrl() { const params = new URLSearchParams(location.search); els.search.value = params.get("q") ?? ""; state.facets = {}; for (const [key, value] of params) if (key !== "q") state.facets[key] = value.split(",").filter(Boolean); state.selectedId = decodeURIComponent(location.hash.slice(1)); }

function renderFacets() {
  const labels = { geography: "Geography", causebase_geography: "Legacy geography", cause: "Cause/domain", beneficiary: "Beneficiaries", activity: "Activities", approach: "Approach", participation: "Participation", organisation: "Organisation", acnc_classification: "ACNC classifications", funding: "Funding sources", dgr: "DGR status" };
  const groups = Object.entries(facetValues(state.entities)).map(([group, values]) => !values.length ? "" : `<details class="facet-group"><summary>${labels[group]}${state.facets[group]?.length ? ` (${state.facets[group].length})` : ""}</summary><div>${values.map(value => `<button class="facet ${state.facets[group]?.includes(value) ? "active" : ""}" data-group="${group}" data-value="${esc(value)}">${esc(label(value))}</button>`).join("")}</div></details>`).join("");
  const active = Object.values(state.facets).flat().length;
  els.facets.innerHTML = `<details class="filters"><summary>Filters${active ? ` (${active} active)` : ""}</summary>${groups}</details>`;
  els.facets.querySelectorAll(".facet").forEach(button => button.onclick = () => { const selected = state.facets[button.dataset.group] ?? []; state.facets[button.dataset.group] = selected.includes(button.dataset.value) ? selected.filter(value => value !== button.dataset.value) : [...selected, button.dataset.value]; apply(); });
}
function renderResults() { els.count.textContent = `${state.filtered.length} organisations`; els.results.innerHTML = state.filtered.map(entity => `<button class="result ${entity.causebase_id === state.selectedId ? "selected" : ""}" data-id="${esc(entity.causebase_id)}"><strong>${esc(entity.display_name)}</strong><span>${esc(entity.navigation_geography?.find(item => item.level === "state_territory")?.label ?? entity.principal_location ?? "")}</span></button>`).join(""); els.results.querySelectorAll("button").forEach(button => button.onclick = () => select(button.dataset.id)); }
function externalLinks(entity) { const number = abn(entity), acnc = entity.acnc_profile_url ?? `https://www.acnc.gov.au/charity/charities?search=${encodeURIComponent(number ?? entity.display_name)}`; return `<ul class="link-list">${entity.website ? `<li><a href="${esc(httpUrl(entity.website))}" target="_blank" rel="noreferrer">Organisation website</a></li>` : ""}${number ? `<li><a href="https://abr.business.gov.au/ABN/View?abn=${encodeURIComponent(number)}" target="_blank" rel="noreferrer">ABN ${esc(number)}</a></li>` : ""}<li><a href="${esc(acnc)}" target="_blank" rel="noreferrer">${entity.acnc_profile_url ? "ACNC Charity Register profile" : "Search ACNC Charity Register"}</a></li>${entity.acnc_ais_url ? `<li><a href="${esc(entity.acnc_ais_url)}" target="_blank" rel="noreferrer">Latest ACNC AIS</a></li>` : ""}<li><a href="${esc(cardUrl(entity))}">Copy/share card link</a></li></ul>`; }
function lineItems(items, registry) { return items?.length ? `<ul>${items.map(item => `<li>${esc(item.label)}: ${esc(formatMoney(item.amount?.normalised_amount, item.amount?.normalised_currency))} ${cite(item.evidence_ids, registry)}</li>`).join("")}</ul>` : ""; }
function tableCitation(rows, registry) { const ids = [...new Set(rows.flatMap(row => row.evidence_ids ?? []))]; return ids.length === 1 ? cite(ids, registry) : ""; }
function statementTable(statement, registry) {
  const title = statement.statement_type === "profit_and_loss" ? "Profit & loss" : statement.statement_type === "financial_position" ? "Assets & liabilities" : statement.statement_type === "cash_flow" ? "Cash flow" : "Changes in equity";
  const rows = statement.rows ?? [];
  const currentLabel = rows.find(row => row.current_period_label)?.current_period_label ?? "Current";
  const sharedCitation = tableCitation(rows, registry);
  return `<section class="reported-statement"><h3>${title} ${sharedCitation}</h3><p class="muted">${esc(statement.statement_title)}</p><table><thead><tr><th>Reported line</th><th>${esc(currentLabel)}</th><th>Comparative</th></tr></thead><tbody>${rows.map(row => `<tr class="statement-${esc(row.row_type)}"><th scope="row" style="padding-left:${Math.min((row.hierarchy_indent ?? 0) * 0.6, 3)}rem">${esc(row.source_label)}${row.canonical_metrics?.length ? ` <small>(${esc(row.canonical_metrics.join(", ").replaceAll("_", " "))})</small>` : ""}</th><td>${row.current_amount ? esc(formatMoney(row.current_amount.normalised_amount, row.current_amount.normalised_currency)) : ""}</td><td>${row.comparative_periods?.[0]?.amount ? esc(formatMoney(row.comparative_periods[0].amount.normalised_amount, row.comparative_periods[0].amount.normalised_currency)) : ""} ${sharedCitation ? "" : cite(row.evidence_ids, registry)}</td></tr>`).join("")}</tbody></table></section>`;
}
function surplusDeficit(finance) { if (!finance?.revenue || !finance?.total_expenses) return "None recorded"; const amount = Number(finance.revenue.normalised_amount) - Number(finance.total_expenses.normalised_amount); return formatMoney(amount, finance.revenue.normalised_currency); }
function headlineMetric(entity, finance, metric) { const amount = finance?.[metric]; return amount ? formatMoney(amount.normalised_amount, amount.normalised_currency) : financialMetricDisplay(entity, metric); }
function functionalAllocations(finance, registry) {
  const rows = finance?.functional_expense_allocations ?? [];
  if (!rows.length) return "";
  const sharedCitation = tableCitation(rows, registry);
  return `<section class="reported-statement"><h4>Use of expenditure ${sharedCitation}</h4><p class="muted">Functional allocation by purpose, separate from statutory expenses by nature. Shares are directly reported; shown dollar figures are approximate mechanical calculations from total expenses.</p><table><thead><tr><th>Reported allocation</th><th>Direct reported share</th><th>Approximate implied amount</th></tr></thead><tbody>${rows.map(row => { const display = functionalAllocationDisplay(row); return `<tr><th scope="row">${esc(row.source_label)}</th><td>${esc(display.share)}</td><td>${esc(display.derivedAmount)} ${sharedCitation ? "" : cite(row.evidence_ids, registry)}</td></tr>`; }).join("")}</tbody></table></section>`;
}
function fundingAndFundraising(entity, finance, registry) {
  const projection = finance?.donations_gifts_bequests;
  if (projection) {
    const display = donationsGiftsBequestsDisplay(projection);
    const fundraisingRow = fundraisingAllocationOnly(finance?.functional_expense_allocations);
    const expenditure = fundraisingRow ? (() => { const item = functionalAllocationDisplay(fundraisingRow); return `<section class="reported-statement"><h4>Fundraising expenditure ${cite(fundraisingRow.evidence_ids, registry)}</h4><p><strong>${esc(item.share)}</strong> of total expenditure</p><p>${esc(item.derivedAmount)} implied by the reported share.</p></section>`; })() : "";
    const methods = entity.fundraising_methods?.length ? `<h4>Fundraising methods</h4><ul>${entity.fundraising_methods.map(item => `<li>${esc(item.method.replaceAll("_", " "))} ${cite(item.evidence_ids, registry)}</li>`).join("")}</ul>` : "";
    return `<section><h3>Funding &amp; fundraising</h3><section class="reported-statement"><h4>Donations, gifts &amp; bequests ${cite(projection.evidence_ids, registry)}</h4><p><strong>${esc(display.amount)}</strong> · ${esc(display.percentage)}</p><p class="muted">Includes:</p><ul>${projection.components.map(item => `<li>${esc(item.source_label)} — ${esc(formatMoney(item.amount.normalised_amount, item.amount.normalised_currency))}</li>`).join("")}</ul></section>${expenditure}${methods}<p class="muted">This section is descriptive and is not a rating or efficiency assessment.</p></section>`;
  }
  const shares = [];
  const funding = shares.length ? `<table><thead><tr><th>Reported revenue source</th><th>Amount</th><th>Share</th></tr></thead><tbody>${shares.map(item => { const display = revenueShareDisplay(item); return `<tr><th scope="row">${esc(item.source_label)}</th><td>${esc(display.amount)}</td><td>${esc(display.percentage)}</td></tr>`; }).join("")}</tbody></table><p class="muted">Shares use each source-labelled revenue row divided by the report’s total income; categories may overlap only where the source itself presents them that way.</p>` : "<p>Funding sources: <strong>not_available_from_source</strong> in the currently acquired evidence.</p>";
  const fundraising = entity.fundraising_methods?.length ? `<h4>Fundraising methods</h4><ul>${entity.fundraising_methods.map(item => `<li>${esc(item.method.replaceAll("_", " "))} ${cite(item.evidence_ids, registry)}</li>`).join("")}</ul>` : "";
  return `<section><h3>Funding &amp; fundraising</h3><h4>Funding sources / revenue</h4>${funding}${fundraising}${functionalAllocations(finance, registry)}<p class="muted">This section is descriptive and is not a rating or efficiency assessment.</p></section>`;
}
function identityFacts(entity, registry) {
  const dgr = entity.tax_statuses?.find(item => item.scheme?.toLowerCase().includes("dgr"));
  const acnc = entity.registrations?.find(item => item.regulator?.toLowerCase().includes("acnc"));
  const rows = [
    ["Legacy subject ID", entity.causebase_id], ["Legal name", entity.legal_name],
    ["ABN", abn(entity) ? `<a href="https://abr.business.gov.au/ABN/View?abn=${encodeURIComponent(abn(entity))}" target="_blank" rel="noreferrer">${esc(abn(entity))}</a>` : null],
    ["ACNC registration", entity.acnc_profile_url ? `<a href="${esc(entity.acnc_profile_url)}" target="_blank" rel="noreferrer">${esc(acnc?.status ?? entity.entity_status ?? "Registered")}</a> ${cite(acnc?.evidence_ids, registry)}` : (acnc?.status ?? entity.entity_status)],
    ["Deductible Gift Recipient", dgr ? `${esc(dgr.status === "endorsed" ? "Yes" : dgr.status ?? "Recorded")} ${dgr.detail ? `(${esc(dgr.detail)})` : ""} ${cite(dgr.evidence_ids, registry)}` : null],
    ["Principal location", entity.principal_location], ["Website", entity.website ? `<a href="${esc(httpUrl(entity.website))}" target="_blank" rel="noreferrer">${esc(entity.website)}</a>` : null],
  ].filter(([, value]) => value);
  return `<dl class="identity-facts">${rows.map(([term, value]) => `<div><dt>${esc(term)}</dt><dd>${value}</dd></div>`).join("")}</dl>${entity.operating_names?.length ? `<p><strong>Operating names:</strong> ${esc(entity.operating_names.join(", "))}</p>` : ""}${entity.former_names?.length ? `<p><strong>Former names:</strong> ${esc(entity.former_names.join(", "))}</p>` : ""}`;
}
function renderHistory(entity, registry) {
  const entries = [...(entity.relationships ?? []).map(item => `${item.status === "historical" ? "Historical" : "Current"} ${esc(item.relationship_type.replaceAll("_", " "))}: ${esc(item.target_causebase_id)}${item.note ? ` — ${esc(item.note)}` : ""} ${cite(item.evidence_ids, registry)}`), ...(entity.former_names ?? []).map(name => `Former name: ${esc(name)}`)];
  if (entity.acnc_ais_url) entries.push(`<a href="${esc(entity.acnc_ais_url)}" target="_blank" rel="noreferrer">Latest submitted ACNC AIS</a>`);
  if (entity.financial_records?.at(-1)?.period?.label) entries.push(`Latest financial observation: ${esc(entity.financial_records.at(-1).period.label)}`);
  return entries.length ? `<section><h2>History &amp; relationships</h2><ul>${entries.map(item => `<li>${item}</li>`).join("")}</ul></section>` : "";
}
function legacyMaterial(entity) {
  const legacy = entity.legacy_unbound;
  if (!legacy) return "";
  const domains = [
    ["Activities", legacy.activities], ["Beneficiaries", legacy.beneficiaries], ["Descriptive geography", legacy.descriptive_geography], ["Classifications", legacy.classifications], ["Funding sources", legacy.funding_sources], ["Fundraising methods", legacy.fundraising_methods],
  ].filter(([, values]) => values?.length).map(([name, values]) => `<h3>${esc(name)}</h3><ul>${values.map(value => `<li>${esc(value.value ?? value.term_label ?? value.source_label ?? value.method ?? JSON.stringify(value))}</li>`).join("")}</ul>`).join("");
  const financial = legacy.financial_records?.length ? `<p>${legacy.financial_records.length} historical financial record${legacy.financial_records.length === 1 ? "" : "s"} retained in the downloadable JSON.</p>` : "";
  return `<section><h2>Legacy public material</h2><p class="muted">Retained from RC4 for transparency, but not represented as evidence-bound v0.5 observations. It does not make coverage observed.</p>${domains}${financial}</section>`;
}
function renderCard(entity) {
  const registry = citations(entity); const taxonomies = new Map(); for (const item of entity.classifications ?? []) { if (!taxonomies.has(item.taxonomy_id)) taxonomies.set(item.taxonomy_id, []); taxonomies.get(item.taxonomy_id).push(item); }
  const refs = [...registry.entries()].map(([id, number]) => { const item = entity.evidence.find(value => value.evidence_id === id); return item ? `<li id="reference-${number}"><strong>[${number}] ${esc(item.title)}</strong> — ${esc(item.publisher ?? item.source_type)}, observed ${esc(item.observed_at)}${item.page ? `, p. ${item.page}` : ""}${item.url ? ` · <a href="${esc(item.url)}" target="_blank" rel="noreferrer">Open source</a>` : ""}</li>` : ""; }).join("");
  const finance = entity.financial_records?.at(-1); const financeIds = entity.financial_records?.flatMap(item => item.evidence_ids) ?? [];
  const participation = entity.participation_observations?.map(item => { const actionUrl = validActionUrl(item.action_url); return `<li>${actionUrl ? `<a href="${esc(actionUrl)}" target="_blank" rel="noreferrer">${esc(item.label)}</a>` : esc(item.label)} ${cite(item.evidence_ids, registry)}</li>`; }).join("");
  els.card.innerHTML = `<header class="card-header"><div><p class="eyebrow">CharityGraph card</p><h1>${esc(entity.display_name)}</h1><p>${esc(entity.legal_name)} · <a href="#${encodeURIComponent(entity.causebase_id)}">${esc(entity.causebase_id)}</a></p></div>${externalLinks(entity)}</header>
    <section><div class="section-title"><h2>About this organisation</h2><a class="edit-link" href="${correctionUrl(entity, "causebase_summary", entity.causebase_summary, cardUrl(entity))}">Suggest correction</a></div><p class="summary">${esc(entity.causebase_summary)} ${cite(entity.summary_evidence_ids, registry)}</p>${identityFacts(entity, registry)}</section>
    <section class="columns"><div><h2>Activities</h2>${list(entity.activities)}</div><div><h2>Beneficiaries</h2>${list(entity.beneficiaries)}</div><div><h2>Geography</h2>${list(entity.geography)}</div></section>${legacyMaterial(entity)}
    <section><h2>Programs</h2>${entity.programs?.length ? entity.programs.map(program => `<article><h3>${esc(program.name)}</h3><p>${esc(program.description ?? "")}</p><p>${esc([...(program.beneficiaries ?? []), ...(program.geography ?? [])].join(" · "))} ${cite(program.evidence_ids, registry)}</p></article>`).join("") : "<p>Program-level records have not yet been processed from the acquired sources.</p>"}</section>
    <section><h2>Participation</h2>${participation ? `<ul>${participation}</ul>` : "<p>Participation opportunities have not yet been processed from the acquired sources.</p>"}</section>
    <section><h2>Financials</h2>${fundingAndFundraising(entity, finance, registry)}<section><h3>Financial reports</h3><h4>Headline metrics</h4><dl class="facts"><div><dt>Revenue / income</dt><dd>${esc(headlineMetric(entity, finance, "revenue"))} ${cite(financeIds, registry)}</dd></div><div><dt>Total expenses</dt><dd>${esc(headlineMetric(entity, finance, "total_expenses"))} ${cite(financeIds, registry)}</dd></div><div><dt>Surplus / deficit</dt><dd>${esc(surplusDeficit(finance))} ${cite(financeIds, registry)}</dd></div><div><dt>Total assets</dt><dd>${esc(headlineMetric(entity, finance, "assets"))} ${cite(financeIds, registry)}</dd></div><div><dt>Total liabilities</dt><dd>${esc(headlineMetric(entity, finance, "liabilities"))} ${cite(financeIds, registry)}</dd></div><div><dt>Net assets / equity</dt><dd>${esc(headlineMetric(entity, finance, "net_assets"))} ${cite(financeIds, registry)}</dd></div></dl>${finance?.statements?.length ? `<h4>Reported financial statements</h4>${finance.statements.map(statement => statementTable(statement, registry)).join("")}` : ""}${functionalAllocations(finance, registry)}</section></section>
    <section><h2>Classifications</h2>${[...taxonomies.entries()].map(([taxonomy, items]) => `<div class="taxonomy-block"><h3>${esc(taxonomyHeading(taxonomy))}</h3><div class="chips">${items.map(item => `<button class="chip" data-taxonomy="${esc(taxonomy)}" data-term="${esc(item.term_id)}">${esc(item.term_label)}</button>`).join("")}</div></div>`).join("") || "<p>None recorded</p>"}</section>
    ${renderHistory(entity, registry)}<section><h2>Sources &amp; data</h2><h3>Source-native records</h3><ul>${(entity.source_native_records ?? []).map(item => `<li><a href="${sourceRecordLocator(item)}">${esc(item.source_family)} record</a> · ${esc(item.dataset_version)}</li>`).join("") || "<li>None recorded</li>"}</ul><h3>References</h3><ol class="evidence-list">${refs}</ol><p><a href="./public/data/cards/${encodeURIComponent(entity.causebase_id)}.json">View JSON</a> · <a href="./public/data/cards/${encodeURIComponent(entity.causebase_id)}.md">View Markdown</a></p></section><footer>CharityGraph ${esc(entity.dataset_version)} · card schema ${esc(entity.card_schema_version)} · editorial policy ${esc(entity.editorial_policy_version)}</footer>`;
  els.card.querySelectorAll(".chip").forEach(button => button.onclick = () => { let group = button.dataset.taxonomy === "acnc-register" ? "acnc_classification" : button.dataset.term.split(".")[0]; if (group === "geography") group = "causebase_geography"; if (["cause", "beneficiary", "activity", "approach", "participation", "organisation", "causebase_geography", "acnc_classification"].includes(group)) { state.facets[group] = [button.dataset.term]; apply(); } });
}
function renderSimilar(entity) { const rows = state.similarities.filter(item => item.causebase_id === entity.causebase_id).sort((a, b) => a.rank - b.rank).map(item => state.entities.find(value => value.causebase_id === item.similar_causebase_id)).filter(Boolean); if (!rows.length) return; const section = document.createElement("section"); section.innerHTML = `<h2>Similar organisations</h2><p class="muted">Descriptive semantic neighbours, not recommendations.</p><ul>${rows.map(item => `<li><button class="link-button" data-similar="${esc(item.causebase_id)}">${esc(item.display_name)}</button></li>`).join("")}</ul>`; els.card.insertBefore(section, els.card.querySelector("footer")); section.querySelectorAll("[data-similar]").forEach(button => button.onclick = () => select(button.dataset.similar)); }
function select(id, push = true) { if (!state.entities.some(entity => entity.causebase_id === id)) return; state.selectedId = id; syncUrl(push); renderResults(); const entity = state.entities.find(item => item.causebase_id === id); renderCard(entity); renderSimilar(entity); }
function apply() { state.filtered = filterWithFacets(state.entities, els.search.value, state.facets); if (!state.filtered.some(entity => entity.causebase_id === state.selectedId)) state.selectedId = state.filtered[0]?.causebase_id ?? null; syncUrl(); renderFacets(); renderResults(); if (state.selectedId) { const entity = state.entities.find(item => item.causebase_id === state.selectedId); renderCard(entity); renderSimilar(entity); } else els.card.innerHTML = "<div class=\"empty\">No organisations match these filters.</div>"; }
async function loadData() { const canonical = await fetch("./public/data/charitygraph.json"); return canonical.ok ? canonical.json() : fetch("./public/data/causebase.json").then(response => response.json()); }
async function init() { try { const [data, similarities] = await Promise.all([loadData(), fetch("./public/data/similarities.json").then(response => response.json()).catch(() => [])]); state.entities = data.entities; state.similarities = similarities; readUrl(); state.filtered = state.entities; if (!state.entities.some(entity => entity.causebase_id === state.selectedId)) state.selectedId = state.entities[0]?.causebase_id; els.feedback.href = correctionUrl(null, "general_feedback", "", location.href); els.search.oninput = apply; addEventListener("popstate", () => { readUrl(); apply(); }); apply(); } catch (error) { els.card.textContent = `CharityGraph data could not be loaded: ${error.message}`; } }
init();
